Enhance orders filters
commercelayer/dashboard-apps pull request #166
Opened 2024-12-05 12:16 UTC by pfferrari

Closes commercelayer/issues-app/issues/285
Closes commercelayer/issues-app/issues/286

## What I did

- Added `partially_authorized` option to `Payment Status` filter
- Added a subset of filters to `Carts` view

## Checklist

- [x] Make sure your changes are tested (stories and/or unit, integration, or end-to-end tests).
- [ ] Make sure to add/update documentation regarding your changes.
- [x] You are **NOT** deprecating/removing a feature.

2024-12-06 11:04 UTC, pfferrari commented
@marcomontalbano @malessani tested by Sara on custom app.. we have her ok to proceed..

2024-12-09 09:41 UTC, malessani requested changes
I would handle also unmanaged statuses in carts like:
<img width="731" alt="Screenshot 2024-12-09 at 10 40 59" src="https://github.com/user-attachments/assets/b89e2aa1-c988-432b-b299-bf416cc9bc57">

2024-12-09 10:17 UTC, marcomontalbano approved these changes

2024-12-09 10:20 UTC, malessani approved these changes

2024-12-09 11:12 UTC, merged